### REQUEST JWT TOKEN
POST http://localhost:8080/academics/api/auth/login
Content-Type: application/json
Accept: application/json

{ "username": "admin", "password": "123" }

### GET ALL USERS
GET http://localhost:8080/academics/api/user
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTczMzkxOTk4MSwiZXhwIjoxNzMzOTIzNTgxfQ.hjlE-v2TUU0PHJlqN-kt02hOU4rtYEcDfYLx_62Xo6yGfo0LzzxTAV6TEQhMM9QN

### GET ALL CUSTOMERS
GET http://localhost:8080/academics/api/customer
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTczMzMxMjI4MSwiZXhwIjoxNzMzMzE1ODgxfQ.REaRGa0ZZpU6v9BENlE_zegrBcjkukRTLA4agNZ85sGTS2xcfqv4obcjFoVcvE3A

### CREATE CUSTOMER
POST http://localhost:8080/academics/api/customer
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTczMzMxMjI4MSwiZXhwIjoxNzMzMzE1ODgxfQ.REaRGa0ZZpU6v9BENlE_zegrBcjkukRTLA4agNZ85sGTS2xcfqv4obcjFoVcvE3A

{
  "username": "tiago",
  "password": "123",
  "name": "Tiago",
  "email": "tiago@mail.pt"
}

### GET CUSTOMER
GET http://localhost:8080/academics/api/customer/tiago
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTczMzMxMjI4MSwiZXhwIjoxNzMzMzE1ODgxfQ.REaRGa0ZZpU6v9BENlE_zegrBcjkukRTLA4agNZ85sGTS2xcfqv4obcjFoVcvE3A

### CREATE SENSOR
POST http://localhost:8080/academics/api/sensor
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTczNjg4MDUwNywiZXhwIjoxNzM2ODg0MTA3fQ.Rh2tAMMC954I_bl586UX94XWpWIyTIYEOtdkr5RNxCSPGVaWAP6_NjWXFgwJM9WW

{
  "sensorType": "Temperature"
}

### GET ALL SENSORS
GET http://localhost:8080/academics/api/sensor
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTczNzEzNzcwMSwiZXhwIjoxNzM3MTQxMzAxfQ.a0ocz4FYJpfLtkm9Jcmuj3hzNfYzrsEuDUnKs-VeRDcUbB-KupMShkqA2pa0xO2S

### GET SENSOR
GET http://localhost:8080/academics/api/sensor/1
Content-Type: application/json
Accept: application/json
//Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTczNjg3Njk0NywiZXhwIjoxNzM2ODgwNTQ3fQ.158D5OxOOXT8Eiaq0aWJ0rrAIXgadLaur8GqZ-NSr_zBiFCnDjApEylWZv4w1CMZ

### DELETE SENSOR
DELETE http://localhost:8080/academics/api/sensor/1
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTczNjg3MzIyNCwiZXhwIjoxNzM2ODc2ODI0fQ.Gt99ReZVIGbv4er8TDyCYdy0gGUs0pb3eeEkAv2Y1sTQ4KE53HX3iy0-D_TXoL9-

### UPDATE SENSOR
PUT http://localhost:8080/academics/api/sensor/2
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTczNzA0NTc5NCwiZXhwIjoxNzM3MDQ5Mzk0fQ.6LGjf1lybIApNV1GsxnIBWhWhAw-QDDjbzaW2ymk7QDsoK_2n_4Ekm1aVDMq-A7b

{
  "currentValue": 10.6,
  "statusType": "Active"
}

### GET PRODUCTS
GET http://localhost:8080/academics/api/product
Accept: application/json
//Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0aWFnbyIsImlhdCI6MTczMjcxNDQzMCwiZXhwIjoxNzMyNzE4MDMwfQ.6C9-XZ4D--nwwrXNpoW4eEiVPT6-Tjnviqw22wTPfgmNjdWdwG0zVFQIhb1aSRdz

### GET PRODUCT
GET http://localhost:8080/academics/api/product/1
Accept: application/json

### GET PRODUCT
GET http://localhost:8080/academics/api/product/search/jonkler
Accept: application/json

### CREATE PRODUCT
POST http://localhost:8080/academics/api/product
Content-Type: application/json
Accept: application/json

{
"name": "teste",
"description": "teste jonkler",
"price": 69,
"productTypeId": 1
}

### UPDATE PRODUCT
PUT http://localhost:8080/academics/api/product/1
Content-Type: application/json
Accept: application/json


{
  "name": "jonkler moment",
  "description": "darkness batman",
  "price": 420,
  "productTypeId": 1
}

### DELETE PRODUCT
DELETE http://localhost:8080/academics/api/product/1
Content-Type: application/json
Accept: application/json

## PRODUCT TYPES ###

### GET PRODUCT TYPES
GET http://localhost:8080/academics/api/product-type
Accept: application/json

### GET PRODUCT
GET http://localhost:8080/academics/api/product-type/1
Accept: application/json

### CREATE PRODUCT TYPE
POST http://localhost:8080/academics/api/product-type
Content-Type: application/json
Accept: application/json

{
  "type": "mr jonk"
}

### UPDATE PRODUCT TYPE
PUT http://localhost:8080/academics/api/product-type/1
Content-Type: application/json
Accept: application/json

{
  "type": "jonkler moment"
}

### DELETE PRODUCT TYPES
DELETE http://localhost:8080/academics/api/product-type/2
Content-Type: application/json
Accept: application/json

### POST ALERT
POST http://localhost:8080/academics/api/alert/
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTczNzE0NzI5NywiZXhwIjoxNzM3MTUwODk3fQ.Sjb0wnpJGAiY9kayNWt3rG8-7w4qTBmrm85RYxxhwV42t9ZMR1EfcU9JM7vqBmTh

{
  "message": "Sensor value exceeded threshold",
  "formattedTimestamp": "2025-01-17 10:00:00",
  "sensorId": 1
}

### GET ALERT
GET http://localhost:8080/academics/api/alert/1
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTczNzE0NzI5NywiZXhwIjoxNzM3MTUwODk3fQ.Sjb0wnpJGAiY9kayNWt3rG8-7w4qTBmrm85RYxxhwV42t9ZMR1EfcU9JM7vqBmTh

### DELETE ALERT
DELETE http://localhost:8080/academics/api/alert/1
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTczNzE0NzI5NywiZXhwIjoxNzM3MTUwODk3fQ.Sjb0wnpJGAiY9kayNWt3rG8-7w4qTBmrm85RYxxhwV42t9ZMR1EfcU9JM7vqBmTh










