### REQUEST JWT TOKEN
POST http://localhost:8080/academics/api/auth/login
Content-Type: application/json
Accept: application/json

{ "username": "admin", "password": "123" }

### GET ALL USERS
GET http://localhost:8080/academics/api/user
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTczMzkxOTk4MSwiZXhwIjoxNzMzOTIzNTgxfQ.hjlE-v2TUU0PHJlqN-kt02hOU4rtYEcDfYLx_62Xo6yGfo0LzzxTAV6TEQhMM9QN

### GET ALL CUSTOMERS
GET http://localhost:8080/academics/api/customer
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTczMzMxMjI4MSwiZXhwIjoxNzMzMzE1ODgxfQ.REaRGa0ZZpU6v9BENlE_zegrBcjkukRTLA4agNZ85sGTS2xcfqv4obcjFoVcvE3A

### CREATE CUSTOMER
POST http://localhost:8080/academics/api/customer
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTczMzMxMjI4MSwiZXhwIjoxNzMzMzE1ODgxfQ.REaRGa0ZZpU6v9BENlE_zegrBcjkukRTLA4agNZ85sGTS2xcfqv4obcjFoVcvE3A

{
  "username": "tiago",
  "password": "123",
  "name": "Tiago",
  "email": "tiago@mail.pt"
}

### GET CUSTOMER
GET http://localhost:8080/academics/api/customer/tiago
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTczMzMxMjI4MSwiZXhwIjoxNzMzMzE1ODgxfQ.REaRGa0ZZpU6v9BENlE_zegrBcjkukRTLA4agNZ85sGTS2xcfqv4obcjFoVcvE3A

### CREATE SENSOR
POST http://localhost:8080/academics/api/sensor
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTczNTU3NDgwMywiZXhwIjoxNzM1NTc4NDAzfQ.fRS7ZbhRHB7ojnlQIW9i0nu0f7WRA8SUcgjLLvXs_3XrdeYghccjkPvS6RR2IA-7

{
  "sensorType": "Temperature"
}

### GET ALL SENSORS
GET http://localhost:8080/academics/api/sensor
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTczNTU3NDgwMywiZXhwIjoxNzM1NTc4NDAzfQ.fRS7ZbhRHB7ojnlQIW9i0nu0f7WRA8SUcgjLLvXs_3XrdeYghccjkPvS6RR2IA-7

### GET ONE SENSOR
GET http://localhost:8080/academics/api/sensor/1
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTczNTU3NDgwMywiZXhwIjoxNzM1NTc4NDAzfQ.fRS7ZbhRHB7ojnlQIW9i0nu0f7WRA8SUcgjLLvXs_3XrdeYghccjkPvS6RR2IA-7